import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import path from "node:path";
import fs from "node:fs";

// package.json sets "type": "module", so this file loads as ESM and __dirname does
// not exist. import.meta.dirname is the ESM equivalent (Node >= 20.11).
const here = import.meta.dirname;

const MOD_SRC = path.resolve(here, "../GeneKerman");
const OUT_DIR = path.resolve(here, "../GameData/BoundlessMissions/WebUI");

/**
 * Single source of truth for the version: read it out of ModVersion.cs rather than
 * duplicating it in package.json, where it would silently drift.
 */
function readModVersion(): string {
  const src = fs.readFileSync(path.join(MOD_SRC, "ModVersion.cs"), "utf8");
  const m = src.match(/public\s+const\s+string\s+Current\s*=\s*"([^"]+)"/);
  if (!m) throw new Error("Could not find ModVersion.Current in ModVersion.cs");
  return m[1];
}

/**
 * The mod refuses to start the bridge unless this manifest matches the running DLL.
 * CKAN installs, manual installs and hand-copied folders coexist, so a mismatched
 * WebUI/ will happen — and a UI calling endpoints the DLL lacks is miserable to debug.
 */
function manifestPlugin(): Plugin {
  return {
    name: "gk-manifest",
    closeBundle() {
      const modVersion = readModVersion();
      fs.writeFileSync(
        path.join(OUT_DIR, "manifest.json"),
        JSON.stringify({ modVersion, builtAt: new Date().toISOString() }, null, 2)
      );
      console.log(`  → wrote manifest.json (modVersion ${modVersion})`);
    },
  };
}

/**
 * Every package below is compiled into the shipped bundle, and MIT, ISC and Apache-2.0
 * all require their copyright notice and licence text to travel with the binary. Only
 * React's and lucide's banners survive minification (esbuild keeps `@license` comments);
 * clsx, tailwind-merge and class-variance-authority carry no banner at all, so without
 * this file their notices would simply be absent from a release.
 *
 * Generated from node_modules rather than hand-maintained, for the reason manifest.json
 * is: a list of dependencies written down twice drifts the first time one is added.
 * `scheduler` is named explicitly because it is react-dom's runtime dependency — in the
 * bundle, but not in our package.json, so reading `dependencies` alone would miss it.
 */
const TRANSITIVE = ["scheduler"];

function noticesPlugin(): Plugin {
  return {
    name: "gk-third-party-notices",
    closeBundle() {
      const pkg = JSON.parse(fs.readFileSync(path.join(here, "package.json"), "utf8"));
      const names = [...Object.keys(pkg.dependencies ?? {}), ...TRANSITIVE].sort();

      const parts = names.map((name) => {
        const dir = path.join(here, "node_modules", name);
        const meta = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
        // Packages disagree on capitalisation and extension: LICENSE, license, LICENSE.md.
        const file = fs.readdirSync(dir).find((f) => /^licen[cs]e/i.test(f));
        if (!file) throw new Error(`No LICENSE file in node_modules/${name}`);
        const text = fs.readFileSync(path.join(dir, file), "utf8").trim();
        return `${"-".repeat(76)}\n${name} ${meta.version} (${meta.license})\n${"-".repeat(76)}\n\n${text}\n`;
      });

      const header = [
        "THIRD-PARTY NOTICES: Boundless Missions in-game browser UI",
        "",
        "The bundle in assets/ is a compiled form of this mod's WebUI/ sources together",
        "with the third-party packages listed below. Boundless Missions itself is licensed",
        "under the GNU General Public License v3.0 (see LICENSE in the mod's repository at",
        "https://github.com/Boundless-Missions/boundlessmissions-modside); the licences",
        "below apply to those packages only, and each is compatible with the GPLv3.",
        "",
        "This file is generated by WebUI/vite.config.ts on every build. Do not edit it.",
        "",
        "",
      ].join("\n");

      fs.writeFileSync(path.join(OUT_DIR, "THIRD-PARTY-NOTICES.txt"), header + parts.join("\n"));
      console.log(`  → wrote THIRD-PARTY-NOTICES.txt (${names.length} packages)`);
    },
  };
}

export default defineConfig({
  plugins: [react(), manifestPlugin(), noticesPlugin()],
  resolve: {
    alias: { "@": path.resolve(here, "src") },
  },
  // Relative asset URLs. Costs nothing today and is what lets the same bundle be
  // hosted by something other than the loopback server later (an embedded renderer,
  // or file://) without a rebuild.
  base: "./",
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    // The mod's CSP is script-src 'self' with no 'unsafe-inline', so nothing may be
    // inlined into index.html as a <script> body.
    assetsInlineLimit: 0,
    sourcemap: false,
    target: "es2020",
  },
  server: {
    // `npm run dev` against a running KSP: proxy /gk and /api to the live bridge so the
    // dev server is same-origin with it, exactly as the shipped bundle is.
    //
    // The bridge picks an ephemeral port per session, so read it out of KSP.log and
    // pass it in:  GK_BRIDGE_PORT=54321 npm run dev
    // Note the handshake nonce is single-use, so you also need a fresh one — click
    // "Reopen in browser" in game and copy the ?k= off the URL it opens.
    proxy: {
      "/gk": `http://127.0.0.1:${process.env.GK_BRIDGE_PORT ?? "5099"}`,
      "/api": `http://127.0.0.1:${process.env.GK_BRIDGE_PORT ?? "5099"}`,
    },
  },
});
